name: Get and cache dependencres
description: Get the dependencies and cache them
runs:
  using: composite
  steps:
    - name: cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('**/package-lock.json')}}
    - name: install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
