name: Container workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/composite-cached-npm