name: docker custom action
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Javascript action
        id: docker-action
        uses: ./.github/actions/docker-sample
        with:
          who-to-greet: 'devops'
      # - name: Print infomation
      #   run: echo "${{ steps.javascript-action.outputs.time }}"