name: Composite custom action
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/composite-cached-npm
        with:
          caching: 'false'
      - name: test the code
        run: echo testing ... 

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/composite-cached-npm
      - name: build the code
        run: echo building ...