# name: Job output

# on:
#   push:
#     branches: [ "main" ]

#   workflow_dispatch:

# jobs:
#   input:
#     runs-on: ubuntu-latest
#     outputs:
#       from_input: ${{ steps.publish.outputs.variable_input }} # use github context `steps`
#     steps:
#       - name: gennerate output
#         run: echo "variable_input='Hello from input job'" >> $GITHUB_OUTPUT
#         id: publish
#   ouput:
#     runs-on: ubuntu-latest
#     needs: input
#     steps:
#       - name: get input from input job
#         run: |
#           echo "${{ needs.input.outputs.from_input }}"
