name: reuseable workflow src
on: workflow_call

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install node version
        uses: actions/setup-node@v3
        with:
          node-version:  14