name: reuse workflow
on: push

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      
      - name: re-use
        uses: https://github.com/daotoan-hd/gh-action-learn/blob/main/.github/workflows/reuse.yaml#L10