name: step conditional

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: echo "installing dependencies"
      - name: run test
        id: run-test
        run: command-failed 2> errors.txt
      - name: upload failed test result
        if: failure() && steps.run-test.outcome == 'failure' # conditonal function and conditional
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: errors.txt

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: get input from input job
        run: |
          echo "Building ..."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: get input from input job
        run: |
          echo "Deploying ... "

  report:
    needs:
      - test
      - build
      - deploy
    steps:
      - name: Output infomation
        run: |
          echo "Something went wrong"
          echo "${{ github }}"
